# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(400, 132)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.energyCostLabel = QtWidgets.QLabel(SettingsDialog)
        self.energyCostLabel.setObjectName("energyCostLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.energyCostLabel)
        self.laborCostLabel = QtWidgets.QLabel(SettingsDialog)
        self.laborCostLabel.setObjectName("laborCostLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.laborCostLabel)
        self.laborCostDoubleSpinBox = QtWidgets.QDoubleSpinBox(SettingsDialog)
        self.laborCostDoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.laborCostDoubleSpinBox.setMaximum(100000.0)
        self.laborCostDoubleSpinBox.setObjectName("laborCostDoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.laborCostDoubleSpinBox)
        self.failureRateLabel = QtWidgets.QLabel(SettingsDialog)
        self.failureRateLabel.setObjectName("failureRateLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.failureRateLabel)
        self.failureRateDoubleSpinBox = QtWidgets.QDoubleSpinBox(SettingsDialog)
        self.failureRateDoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.failureRateDoubleSpinBox.setMaximum(100.0)
        self.failureRateDoubleSpinBox.setObjectName("failureRateDoubleSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.failureRateDoubleSpinBox)
        self.energyCostDoubleSpinBox = QtWidgets.QDoubleSpinBox(SettingsDialog)
        self.energyCostDoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.energyCostDoubleSpinBox.setDecimals(4)
        self.energyCostDoubleSpinBox.setObjectName("energyCostDoubleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.energyCostDoubleSpinBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.savePrinterButton = QtWidgets.QPushButton(SettingsDialog)
        self.savePrinterButton.setObjectName("savePrinterButton")
        self.verticalLayout.addWidget(self.savePrinterButton)

        self.retranslateUi(SettingsDialog)
        self.savePrinterButton.clicked.connect(SettingsDialog.close)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)
        SettingsDialog.setTabOrder(self.energyCostDoubleSpinBox, self.laborCostDoubleSpinBox)
        SettingsDialog.setTabOrder(self.laborCostDoubleSpinBox, self.failureRateDoubleSpinBox)
        SettingsDialog.setTabOrder(self.failureRateDoubleSpinBox, self.savePrinterButton)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.energyCostLabel.setText(_translate("SettingsDialog", "Energy Cost:"))
        self.laborCostLabel.setText(_translate("SettingsDialog", "Labor Cost:"))
        self.laborCostDoubleSpinBox.setPrefix(_translate("SettingsDialog", "$ "))
        self.failureRateLabel.setText(_translate("SettingsDialog", "Failure Rate:"))
        self.failureRateDoubleSpinBox.setSuffix(_translate("SettingsDialog", " %"))
        self.energyCostDoubleSpinBox.setSuffix(_translate("SettingsDialog", " $/kWh"))
        self.savePrinterButton.setText(_translate("SettingsDialog", "Save"))
